
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 22 00:52:13 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 38;
  public static final int LBRACKET = 41;
  public static final int INCREMENT = 22;
  public static final int CONST = 39;
  public static final int GEQUAL = 32;
  public static final int NUMCONST = 47;
  public static final int LPAREN = 6;
  public static final int GREATER = 31;
  public static final int SEMI = 5;
  public static final int CONTINUE = 20;
  public static final int INTERFACE = 46;
  public static final int LESS = 33;
  public static final int FOR = 18;
  public static final int MINUS = 26;
  public static final int DECREMENT = 23;
  public static final int RPAREN = 7;
  public static final int AND = 25;
  public static final int RELEQUAL = 29;
  public static final int OR = 24;
  public static final int COMMA = 8;
  public static final int CLASS = 43;
  public static final int DIV = 36;
  public static final int PLUS = 11;
  public static final int IF = 16;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 12;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int PERCENT = 37;
  public static final int NUMBER = 14;
  public static final int BREAK = 19;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int ENUM = 40;
  public static final int LEQUAL = 34;
  public static final int READ = 21;
  public static final int CHARCONST = 48;
  public static final int NEQUAL = 30;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 44;
  public static final int PROG = 2;
  public static final int IMPLEMENTS = 45;
  public static final int PRINT = 9;
}

